# Generated by Django 2.0 on 2018-04-21 00:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fechaCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.TextField(),
        ),
    ]
